login/urls.py
from django.conf.urls import url
from django.urls import path,include
from login import views

app_name='login'

urlpatterns=[

path('register/',views.register,name='register'),
path('userlogin/',views.user_login,name='userlogin'),
path('dashboard/',views.dashboard,name='dashboard'),
path('user_logout/',views.user_logout,name='user_logout'),
path('news/',views.news,name='news'),
path('stockprice/',views.stockprice,name='stockprice'),
#path('dashboard/create', views.UserStockDisplayCreateView.as_view(), name='stock_create'),

]

wdsapp/urls.py
from django.contrib import admin
from django.urls import path,include
from login import views


urlpatterns = [
    path('',views.index,name="index"),
    path('login/',include('login.urls')),
    path('admin/', admin.site.urls),
    path('user_logout/',views.user_logout,name="user_logout"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('news/',views.News,name="news"),
    path('brokerdashboard/',views.brokerdashboard.as_view(),name="brokerdashboard"),
    path('dashboard/<int:pk>/',views.deleteUserStockDisplay.as_view(),name="UserStockDisplaydelete"),
    path('dashboard/create', views.UserStockDisplayCreateView.as_view(), name='stock_create'),


]

login/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)


    def __str__(self):
        return self.user.username

class Stock(models.Model):
    StockName = models.CharField(blank=True, max_length=100)
    CurrentPrice = models.FloatField(null=True,blank=True)
    def __str__(self):
        return self.StockName

class UserStockDisplay(models.Model):
    #TeamId=models.CharField(blank=True, max_length=100)
    author=models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    StockName = models.ForeignKey(Stock,on_delete=models.CASCADE)
    NumberOfStock = models.IntegerField(blank=False, null=False)
    SellingPrice = models.FloatField(blank=False,null=False)

class News(models.Model):
    Id = models.AutoField(primary_key=True)
    StockNews = models.TextField(blank=True)

login/forms.py
from django import forms
from django.contrib.auth.models import User
from login.models import *
from django.http import HttpResponseRedirect,HttpResponse

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('username','email','password')


class UserStockDisplayForm(forms.ModelForm):
    class Meta():
        model=UserStockDisplay
        fields=['StockName','NumberOfStock','SellingPrice']

login/views.py
from django.shortcuts import render,redirect
from login.forms import *
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.views.generic.edit import CreateView,UpdateView,DeleteView

from login.models import *
from django.contrib.auth.models import User
from django.views import generic

from django.urls import reverse_lazy

# Create your views here.
def index(request):
    return render(request,'login/index.html')


def register(request):
    user_form=UserForm()
    registered= False
    if request.method=="POST":

        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if (user_form.is_valid() and profile_form.is_valid()):
            user=user_form.save()
            user.set_password(user.password)
            user.save()


            profile=profile_form.save(commit=False)
            profile.user=user #onetoone relation
            if profile_pic in request.FILES:
                profile.profile_pic= request.FILES['profile_pic']

            profile.save()

            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,'login/registration.html',{'username':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    print("login page attempt")
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        print(username)
        print(password)


        user=authenticate(username=username,password=password)

        if user is not None:
            #if user.is_active():
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            #else:
                #return HttpResponse("Account Not Active")
        else:
            print("false login")
            return HttpResponseRedirect(reverse('index'))
    else:
        print("render part ran successfully")
        return render(request,'login/userlogin.html')


@login_required
def user_logout(request):
    print("logout")
    logout(request)
    return HttpResponseRedirect(reverse('index'))



@login_required
def dashboard(request):


#     if request.method=="POST":
#          dash_form=UserStockDisplayForm(data=request.POST)
#          if (dash_form.is_valid()):
#              print(request.user.username)
#              #dash_form.TeamId=request.user.username
#              dash_form.author=UserProfileInfo.objects.get(user=request.user)
#              dash_form.save()

      user_dashdata=UserStockDisplay.objects.filter(author=request.user)
      UserStockDisplayDic={'dashdata':user_dashdata}
      return render(request,'login/dashboard.html',{'dashdata':user_dashdata})

class UserStockDisplayCreateView(LoginRequiredMixin,generic.CreateView):
	model=UserStockDisplay
	form_class=UserStockDisplayForm
	template_name='login/userstockcreate.html'

	def form_valid(self,form):
		userStockDisplay=form.save(commit=False)
        # form.instance.author = self.request.user
		userStockDisplay.author=self.request.user
		userStockDisplay.save()
		return redirect('login:dashboard')





@login_required
def news(request):
    news_list=News.objects.all()
    NewsDic={'news':news_list}
    return render(request,'login/news.html',context=NewsDic)


@login_required
def stockprice(request):
    stock_list=Stock.objects.all()
    StockDic={'stocks':stock_list}
    return render(request,'login/stockprice.html',context=StockDic)



class brokerdashboard(generic.ListView):
    template_name='login/brokerdashboard.html'
    context_object_name='brokerdashdata'

    def get_queryset(self):
        return UserStockDisplay.objects.all().order_by('StockName')


class deleteUserStockDisplay(generic.DeleteView):
    print("deleteblock")
    template_name='login/dashboard.html'
    model=UserStockDisplay
    success_url =reverse_lazy('login:dashboard')

wdsapp/login/views.py
from django.shortcuts import render,redirect
from login.forms import *
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.views.generic.edit import CreateView,UpdateView,DeleteView

from login.models import *
from django.contrib.auth.models import User
from django.views import generic

from django.urls import reverse_lazy

# Create your views here.
def index(request):
    return render(request,'login/index.html')


def register(request):
    user_form=UserForm()
    registered= False
    if request.method=="POST":

        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if (user_form.is_valid() and profile_form.is_valid()):
            user=user_form.save()
            user.set_password(user.password)
            user.save()


            profile=profile_form.save(commit=False)
            profile.user=user #onetoone relation
            if profile_pic in request.FILES:
                profile.profile_pic= request.FILES['profile_pic']

            profile.save()

            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,'login/registration.html',{'username':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    print("login page attempt")
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        print(username)
        print(password)


        user=authenticate(username=username,password=password)

        if user is not None:
            #if user.is_active():
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            #else:
                #return HttpResponse("Account Not Active")
        else:
            print("false login")
            return HttpResponseRedirect(reverse('index'))
    else:
        print("render part ran successfully")
        return render(request,'login/userlogin.html')


@login_required
def user_logout(request):
    print("logout")
    logout(request)
    return HttpResponseRedirect(reverse('index'))



@login_required
def dashboard(request):


#     if request.method=="POST":
#          dash_form=UserStockDisplayForm(data=request.POST)
#          if (dash_form.is_valid()):
#              print(request.user.username)
#              #dash_form.TeamId=request.user.username
#              dash_form.author=UserProfileInfo.objects.get(user=request.user)
#              dash_form.save()
#
      user_dashdata=UserStockDisplay.objects.all()
      UserStockDisplayDic={'dashdata':user_dashdata}
      return render(request,'login/dashboard.html',{'dashdata':user_dashdata})

class UserStockDisplayCreateView(LoginRequiredMixin,generic.CreateView):
	model=UserStockDisplay
	form_class=UserStockDisplayForm
	template_name='login/userstockcreate.html'

	def form_valid(self,form):
		userStockDisplay=form.save(commit=False)
        # form.instance.author = self.request.user
		userStockDisplay.author=self.request.user
		userStockDisplay.save()
		return redirect('login:dashboard')





@login_required
def news(request):
    news_list=News.objects.all()
    NewsDic={'news':news_list}
    return render(request,'login/news.html',context=NewsDic)


@login_required
def stockprice(request):
    stock_list=Stock.objects.all()
    StockDic={'stocks':stock_list}
    return render(request,'login/stockprice.html',context=StockDic)



class brokerdashboard(generic.ListView):
    template_name='login/brokerdashboard.html'
    context_object_name='brokerdashdata'

    def get_queryset(self):
        return UserStockDisplay.objects.all()


class deleteUserStockDisplay(generic.DeleteView):
    print("deleteblock")
    template_name='login/dashboard.html'
    model=UserStockDisplay
    success_url =reverse_lazy('login:dashboard')

wdsapp/templates/login/dashboard.html
{% extends 'login/login.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Welcome to Dashboard</h1>
<div class="row">
  <div class="col-4">



    <div><a style="margin-top:10px;width:100%"  class="btn btn-warning transparent" href="{% url 'stock_create' %}">Add Stock</a></div>
  </form>
  </div>
  <div class="col-8">
    Your Current deals
    <table class="table table-striped table-bordered table-hover table-condensed">
      <thead>
        <th>Stock Name</th>
        <th>NumberOfStock</th>
        <th>Price</th>
        <th>Action</th>
      </thead>
{% if dashdata %}
      {% for dd in dashdata %}
      <tr>
        <td>{{ dd.StockName }}</td>
        <td>{{ dd.NumberOfStock }}</td>
        <td>{{ dd.SellingPrice }}</td>


        <td><form action="{% url 'UserStockDisplaydelete' dd.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="dd_id" value="{{dd.id}}"/>
            <button type="submit" class="btn btn-danger" name="button" value="Delete">Delete</button>
            </form>
        </td>

      </tr>
      {%endfor%}
{% endif %}
    </table>



  </div>

</div>

</div>




</div>
{% endblock %}

wdsapp/templates/login/index.html
{% extends 'login/login.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Welcome TO WDS version 4.0</h1>
</div>
{% endblock %}

wdsapp/templates/login/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <div class="container-fluid">
    <nav class="navbar navbar-expand-sm bg-light navbar-light">

        <ul class="nav navbar-nav">
          <li><a class="navbar-link" href="{% url 'index' %}">&nbsp Home </a></li>


          {% csrf_token %}
          {% if user.is_staff %}
          <li><a class="navbar-band" href="{% url 'brokerdashboard' %}">&nbsp Broker </a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">&nbsp Admin </a></li>
          <!--<li><a class="navbar-band" href="{% url 'login:register' %}">&nbsp Register </a></li>-->
          {% endif %}



          {% if user.is_authenticated %}

          <li><a class="navbar-link" href="{% url 'login:news' %}">&nbsp News </a></li>
          <li><a class="navbar-link" href="{% url 'login:stockprice' %}">&nbsp Stock Price </a></li>
          <li><a class="navbar-link" href="{% url 'login:dashboard' %}">&nbsp dashboard </a></li>
          <li><a class="navbar-link" href="{% url 'login:user_logout' %}">&nbsp logout </a></li>

          {% else %}
            <li><a class="navbar-link" href="{% url 'login:userlogin' %}">&nbsp Login </a></li>
          {% endif %}

          


        </ul>
     </div>
   </nav>
<div class="container-fluid">
  {% block body_block %}
  {% endblock %}
</div>

  </body>
  <!-- Footer -->
  <footer class="page-footer font-small black">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2018 Copyright:
      <a href=""> econclub</a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->

</html>

wdsapp/templates/login/news.html
{% extends 'login/login.html' %}
{% load staticfiles %}
{% block body_block %}
<table class="table table-striped table-bordered table-hover table-condensed">
  <thead>
    <th align="right">Serial</th>
    <th>News</th>
  </thead>
  {% for nw in news %}
  <tr>
    <td>{{ nw.Id }}</td>
    <td>{{ nw.StockNews }}</td>
  </tr>
  {%endfor%}
</table>


{% endblock %}

wdsapp/templates/login/userlogin.html
{% extends 'login/login.html' %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">

  <h1>Login Page</h1>

  <form action="{% url 'login:userlogin' %}" method="post">
    {% csrf_token %}

      <label for="Username">username</label>
      <input type="text" class="form-control"  placeholder="Enter user name" name="username">


      <label for="Password">Password</label>
      <input type="password" class="form-control" name="password" placeholder="Password">


    <button type="submit" class="btn btn-primary">Submit</button>
  </form>






</div>

{% endblock %}

wdsapp/templates/login/userstockcreate.html
{% extends 'login/login.html' %}
{% load staticfiles %}
{% block body_block %}

<h1>hello</h1>
<form method="POST" action="" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}

	<button class="btn btn-success" type="submit">Yup!Done</button>
</form>
{% endblock %}